# Generated by Django 3.0.4 on 2020-03-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0005_auto_20200325_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowleveltask',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
