# Generated by Django 3.0.4 on 2020-03-26 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0006_auto_20200325_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='highleveltask',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
