# Generated by Django 3.0.4 on 2020-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0008_auto_20200326_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highleveltask',
            name='finish_date',
            field=models.DateTimeField(),
        ),
    ]
