# Generated by Django 3.0.4 on 2020-03-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='material',
            new_name='task',
        ),
    ]
