# Generated by Django 3.0.4 on 2020-03-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0011_auto_20200327_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowleveltask',
            name='high_level_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_task', to='trackerApp.HighLevelTask'),
        ),
    ]
